version: 2.1

executors:
  scala_211: &scala_211
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SCALA_VERSION: 2.11.11
    
  scala_212: &scala_212
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      SCALA_VERSION: 2.12.2


commands:
  build_and_test:
    description: "build and test"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
          - v2-dependencies-
      - run:
          name: Compile
          command: sbt ++$SCALA_VERSION compile
      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2/cache
          key: v2-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Run unit and integration tests
          command: sbt ++$SCALA_VERSION test
  
  publish:
    description: "publish"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}-{{ checksum ".circleci/config.yml" }}
          - v2-dependencies-
      - run:
          name: Publish
          command: .circleci/release.sh


jobs:
  build_211:
    executor: scala_211
    steps:
      - build_and_test
  
  build_212:
    executor: scala_212
    steps:
      - build_and_test
        
  publish_211:
    executor: scala_211
    steps:
      - publish
  
  publish_212:
    executor: scala_212
    steps:
      - publish


workflows:
  version: 2.1
  test_and_publish:
    jobs:
      - build_211:
          context: PagerDuty
      - build_212:
          context: PagerDuty
      - publish_211:
          requires:
            - build_211
          context: PagerDuty
          filters:
            branches:
              only: master
      - publish_212:
          requires:
            - build_212
          context: PagerDuty
          filters:
            branches:
              only: master
